### ISSUE TITLE
Support  server-owned object aggregates

### ISSUE THREAD

**Issue by harlem88** [astarte-platform/astarte-device-sdk-qt5#61]
The current version of the Astarte SDK Qt5 does not have support for server-owned object aggregates.

**Comment by rbino** [comment]
The current implementation of `AstarteGenericConsumer` assumes individual aggregation in its [dispatch](https://github.com/astarte-platform/astarte-device-sdk-qt5/blob/c13ef699dcc9bd3fe811e162711cb8bd1c2ee3fe/astarte-utils/AstarteGenericConsumer.cpp#L57) function.
A possible draft to implement this is:
- Add an `aggregation` member that will be set to individual or object in the SDK when [creating the consumer](https://github.com/astarte-platform/astarte-device-sdk-qt5/blob/c13ef699dcc9bd3fe811e162711cb8bd1c2ee3fe/astarte-device-sdk/AstarteDeviceSDK.cpp#L181) for the specific interface
- Branch on the `aggregation` field in `dispatch`, possibly implementing two helpers to reduce nesting: `dispatchIndividual` and `dispatchObject`. `dispatchIndividual` will contain the current `dispatch` implementation, while `dispatchObject` should look into the `v` key and iterate all the keys in the subdocument, validate them, convert them to a native type, put them in a `QVariantHash` in the same format we use to publish aggregates and call `receiveData` with the built map.
This solution probably implies adding some support to convert a BSON document to a QVariantHash in `BSONDocument` and/or `ConsumerAbstractAdaptor`. Note that the `dispatch` interface must remain the same since it must match the one expected in `ConsumerAbstractAdaptor`
